# **Numpy**


>**Defination:** NumPy which stands for Numerical Python, is a Python library used for working with arrays. It provides a high-performance multidimensional array object, and a large collection of mathematical functions that operate on these arrays. 

NumPy is used in a wide variety of applications, including:

**➤ Data science and machine learning**<br>
NumPy is used to store and manipulate large datasets, and to perform complex mathematical operations on them.

**➤Scientific computing** <br>
NumPy is used to solve complex scientific problems, such as simulating physical systems and modeling financial markets.

**➤ Image processing**<br> 
NumPy is used to store and manipulate images, and to perform image processing operations such as filtering and edge detection.

**➤ Signal processing**<br>
NumPy is used to store and manipulate signals, and to perform signal processing operations such as filtering and Fourier analysis.

Here are some of the reasons why we use NumPy:

- NumPy arrays are faster and more efficient than Python lists for performing mathematical operations.
- NumPy provides a wide range of mathematical functions that are optimized for working with arrays.
- NumPy is compatible with other popular Python libraries, such as pandas and matplotlib. NumPy is used to store and manipulate large datasets, and to perform complex mathematical operations on them.
- Scientific computing: NumPy is used to solve complex scientific problems, such as simulating physical systems and modeling financial markets.
- Image processing: NumPy is used to store and manipulate images, and to perform image processing operations such as filtering and edge detection.
- Signal processing: NumPy is used to store and manipulate signals, and to perform signal processing operations such as filtering and Fourier analysis.
Here are some of the reasons why we use NumPy:

- NumPy arrays are faster and more efficient than Python lists for performing mathematical operations.
- NumPy provides a wide range of mathematical functions that are optimized for working with arrays.
- NumPy is compatible with other popular Python libraries, such as pandas and matplotlib.

In [53]:
import numpy as np
import pandas as pd

**1) arange()**<br>
np.arange(start, stop, step): Create an array with a range of values.

In [54]:
one_paramter=np.arange(5)
two_paramters=np.arange(1,5)
three_paramters=np.arange(2,10,2)
print(f"With 1 parameter:{one_paramter}\nShape of array is:{one_paramter.shape}")
print(f"With 2 parameters:{two_paramters}\nShape of array is:{two_paramters.shape}")
print(f"With 3 parameters:{three_paramters}\nShape of array is:{three_paramters.shape}")



# Making 2D Arrays from Arange Method
one_paramter_2D=one_paramter[np.newaxis,:]
print(f"2D with 1 parameter:{one_paramter_2D}\nShape of array is:{one_paramter_2D.shape}")

one_paramter_2D=one_paramter[:,np.newaxis]
print(f"2D with 1 parameter:{one_paramter_2D}\nShape of array is:{one_paramter_2D.shape}")





With 1 parameter:[0 1 2 3 4]
Shape of array is:(5,)
With 2 parameters:[1 2 3 4]
Shape of array is:(4,)
With 3 parameters:[2 4 6 8]
Shape of array is:(4,)
2D with 1 parameter:[[0 1 2 3 4]]
Shape of array is:(1, 5)
2D with 1 parameter:[[0]
 [1]
 [2]
 [3]
 [4]]
Shape of array is:(5, 1)


**2) array()**<br>
np.array(): Create an array from a list or tuple.

In [55]:
# 1D Array.
a=np.array([1,2,3,4,5])
print(a)

# some array attribues

print("Type of a is:",type(a))
print("Length of a is:",len(a))
print("Dimention of a is:",a.ndim)
print("Total Elements  of a are:",a.size)
print("Shape  of a is:",a.shape)
print('-'*50)
# 2D Array
b=np.array([(1,2,3,4,5),(1,2,3,4,5)])
print(b)



# some array attribues
print("Type of b is:",type(b))
print("Length of b is:",len(b))
print("Dimention of b is:",b.ndim)
print("Total Elements  of b are:",b.size)
print("Shape  of b is:",b.shape)

[1 2 3 4 5]
Type of a is: <class 'numpy.ndarray'>
Length of a is: 5
Dimention of a is: 1
Total Elements  of a are: 5
Shape  of a is: (5,)
--------------------------------------------------
[[1 2 3 4 5]
 [1 2 3 4 5]]
Type of b is: <class 'numpy.ndarray'>
Length of b is: 2
Dimention of b is: 2
Total Elements  of b are: 10
Shape  of b is: (2, 5)


**3) zeros()**<br>
np.zeros(shape): Create an array filled with zeros.


In [56]:
zeros=np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**4) ones()**<br>
np.ones(shape): Create an array filled with ones.

In [57]:
ones=np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**5) full()**<br>
np.full(shape,value): Create an array filled with desire value.

In [58]:
fives=np.full((3,4),5)
fives

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

**6) eye()**<br>
np.eye(Size): Create an identity matrix of Size x Size .

In [59]:
identity=np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**7) eys()**<br>
np.eye(Size): Create an identity matrix of Size x Size .

# **Math Operations**

In [60]:
a=np.arange(6)
b=np.arange(6)


In [61]:
# Addtion

# Method 1

add=a+b
add

# Method 2
add=np.add(a,b)
add

array([ 0,  2,  4,  6,  8, 10])

In [62]:
# Subtraction

# Method 1

sub=a-b
sub

# Method 2
sub=np.subtract(a,b)
sub

array([0, 0, 0, 0, 0, 0])

In [63]:
# Multiplications

# Method 1

Mul=a*b
Mul

# Method 2
Mul=np.multiply(a,b)
Mul

array([ 0,  1,  4,  9, 16, 25])

In [64]:
# Division

# Method 1
a=np.arange(1,5)
b=np.arange(1,5)
Div=a/b
Div

# Method 2
# Div=np.divide(a,b)
# Div

array([1., 1., 1., 1.])

In [65]:
# Exponent

# Method 1

Exp=a**2
Exp


array([ 1,  4,  9, 16])